#!/bin/bash
#SBATCH --chdir /scratch/lips/ML-Project2/
#SBATCH --nodes 11
#SBATCH --ntasks 176
#SBATCH --ntasks-per-node 16 # allocate 10GB/task
#SBATCH --cpus-per-task 1
#SBATCH --mem 160G
#SBATCH --time 4:00:00 
echo STARTING AT `date`
export MV2_ENABLE_AFFINITY=0 # disable affinity to make each task use seperate cpus
srun python -m mpi4py.futures /scratch/lips/ML-Project2/mpi/mpi_bagging_deregularization.py
echo FINISHED at `date`
